porcelainarts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('porcelainart.urls', namespace='porcelainart')),
    url(r'^management', include('management.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.conf.urls import url
from .views import *

app_name = 'shop'
urlpatterns = [
    url(r'^contact/$', contact, name='contact'),
    url(r'success/', successView, name='success'),
    url(r'error/', errorView, name='error'),
    url(r'^search-results/$', product_query, name='search-results'),
    url(r'^$', product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),


]

templates/porcelainarts/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Porcelain-Arts</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
	<style>
		.navbar-nav li:hover > ul.dropdown-menu {
			display: inline-flex;
		}

		#product-img {
            display: block;
            max-width: 100%;
            margin-right: auto;
            margin-left: auto;

        }
        #item-container{
            padding-left: 15px;
            padding-bottom: 20px;
        }
        #item-container a{
            font-family: "Times New Roman", Times, serif;
            text-transform: uppercase;
            text-align: center;
            margin-bottom : 0px;
        }
         #item-container p{
            font-family: "Times New Roman", Times, serif;
            text-transform: uppercase;
            text-align: center;
            margin-bottom : 0px;
        }

        #main{
            display: grid;
            grid-gap: 10px;
            grid-template: repeat(2, 1fr) / repeat(5, 1fr);
            grid-auto-flow: row;

        }
        #title{
            text-align: center;
            font-family: "Times New Roman", Times, serif;
            text-transform: uppercase;
        }
        #ul_prona_detail{
            width: max-content;
            height: 100%;
            width: 100%;
            display: grid;
            grid-gap: 10px;
            grid-template: repeat(2, 1fr) / repeat(5, 1fr);
            grid-auto-flow: row;
            list-style-type: none;
        }
         #ul_prona_detail1{
            width: max-content;
            height: 100%;
            width: 100%;
            display: grid;
            grid-gap: 10px;

            grid-auto-flow: row;
            list-style-type: none;
        }
        #li_prona_detail{
            width: 200px;
            margin-right: 50px;
            padding-right: 15px;
            padding-left: 15px;
            padding-bottom: 10px;
            border-radius: 15px;

         }
        .card-title{
            text-align: center;
            text-transform: uppercase;
        }
        .card-text{
            text-align: center;
        }
        .text-muted{
            text-align: center;
        }
        #test.dropdown-menu{
            display: contents;
            }

	</style>
</head>


<body>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><a href="#">Albanian </a><a href="#">English </a>
            <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'porcelainart:search-results'  %}">
                <div class="form-group" >
                    <input type="text" class="input-sm hidden-xs form-control" id = "search" name="search" placeholder="Kërko produktin">
                </div>
                <button type="submit"  class="btn btn-default btn-sm hidden-xs glyphicon glyphicon-search" id = "submit"></button>
            </form>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="djathas"><a href="#">Map </a><a>|</a><a href="#">Wish List</a></div>
    </div>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand navbar-link" href="#">
                    <img class="img-responsive" src="{% static 'img/logo.png' %}" alt="Porcelain-Arts" width="140" height="auto" style="margin-top: -15px;padding-top: 1.5px;"></img>
                </a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active" role="presentation"><a href="{% url 'porcelainart:product_list' %}">Home </a></li>
                    <li role="presentation"><a href="#">About Us</a></li>
                    <li class="dropdown hidden-xs hidden-md hidden-sm"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Produktet <span class="caret"></span></a>
                        <ul class="dropdown-menu " role="menu">
                            <li class="dropdown-submenu">
                                <li href="#">
                                    {% block category %} {% endblock%}
                                </li>
							</li>
                        </ul>
                    </li>
                    <li class="dropdown hidden-md hidden-lg hidden-xl" ><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Produktet <span class="caret"></span></a>
                        <ul id="test" class="dropdown-menu "  role="menu">
                            <li class="dropdown-submenu">
                                <li href="#">
                                    {% block category1 %} {% endblock%}
                                </li>
							</li>
                        </ul>
                    </li>
                    <li role="presentation"><a href="{% url 'porcelainart:contact' %}">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% if category or  form or queryset_list or product%}{% else %}
        <div class="carousel slide" data-ride="carousel" id="carousel-1">
            {% include 'porcelainarts/Products/carousel.html' %}
        </div>
    {% endif %}

    <section style="padding-top: 20px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <div class="row hidden-xs hidden-md hidden-sm" >
                        <ul id="ul_prona_detail">
                          {% block content %}{% endblock %}
                        </ul>
                    </div>
                    <div class="row hidden-md hidden-lg hidden-xl" >
                        <ul id="ul_prona_detail1">
                          {% block content1 %}{% endblock %}
                        </ul>
                    </div>
                </div>
            </div>
            <nav>

            {% include 'porcelainarts/Products/paginator.html' with page=products %}
        </nav>
        </div>
    </section>
    <section class="features">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2>Fantastic Features</h2>
                    <p>Dekoroni shtepine tuaj me porcelan te personalizuar sipas deshires tuaj. </p>
                </div>
            </div>
        </div>
    </section>
    <footer class="site-footer">
        <div class="container">
            <div class="row" id="footer-button">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'porcelainart:search-results'  %}">
                        <div class="form-group" >
                            <input type="text" class="input-sm form-control" id = "search" name="search" placeholder="Kërko produktin">
                            <button type="submit"  class="btn btn-default btn-sm glyphicon glyphicon-search" id = "submit"></button>
                        </div>

                    </form>
                     <h5 class="text-right">Procelain Arts © 2018</h5>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 social-icons" id="footer">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#" target="_top" id="top" class="glyphicon glyphicon-arrow-up" style="float: right;"></a>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>